language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements-test.txt
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then travis_retry pip install ordereddict; fi
# command to run tests
script: nosetests
